const other = [
    {
        title:'评价我的',
        icon:require('../../assets/images/home/pjwd.png'),
        router:'',
        width:19,
        height:21
    },
    {
        title:'我的地址',
        icon:require('../../assets/images/home/wddz.png'),
        router:'',
        width:18.5,
        height:21
    },
    {
        title:'旅行基金',
        icon:require('../../assets/images/home/lxjj.png'),
        router:'',
        width:19,
        height:21.5
    },
    {
        title:'帮助与反馈',
        icon:require('../../assets/images/home/bzyfk.png'),
        router:'',
        width:21,
        height:21
    }
];
export default other
